name: deepseek
description: >
  A DeepSeek client for dart and flutter. Seamless integration of AI models for text generation and chat.

version: 0.0.1
repository: https://github.com/tempo-riz/deepseek-dart

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
