name: deepseek
description: >
  A DeepSeek client for dart and flutter. Seamless integration of AI models for text generation and chat.

version: 1.0.0
repository: https://github.com/tempo-riz/deepseek-dart

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.24.0
